### ISSUE TITLE
Package stub works for getNamespace but not as.environment(paste0('package:', ...

### ISSUE THREAD

**Issue by peterhurford** [robertzk/testthatsomemore#15]
Having a problem with https://github.com/robertzk/testthatsomemore/blob/master/R/stub.R#L60-L62 where the function I want exists in `getNamespace(package_name)` but doesn't exist in  `list(as.environment(paste0('package:', package_name)`.

**Comment by robertzk** [comment]
Thanks, will look!

**Comment by robertzk** [comment]
@peterhurford Any chance you can post a reproducible example?

**Comment by peterhurford** [comment]
@robertzk Unfortunately I don't remember. We can close and I can reopen if I ever come across it again.

**Comment by peterhurford** [comment]
My best guess is that it comes from when you mock things that aren't on the search path. e.g., in vanilla R with no non-base libraries loaded:

```R
> getNamespace("dplyr")
<environment: namespace:dplyr>
> as.environment(paste0('package:', package_name))
Error in paste0("package:", package_name) :
  object 'package_name' not found
> as.environment(paste0('package: dplyr'))
Error in as.environment(paste0("package: dplyr")) :
  no item called "package: dplyr" on the search list
```

**Comment by robertzk** [comment]
I think it's `as.environment("package:dplyr")`.
