### ISSUE TITLE
Do mocks make package_stub obsolete?

### ISSUE THREAD

**Issue by robertzk** [robertzk/testthatsomemore#3]
https://github.com/hadley/testthat/blob/master/R/mock.r

**Comment by peterhurford** [comment]
I just came here wondering about this myself.

I'd err on the side of testthat functionality over testthatsomemore functionality wherever possible.  Does `package_stub` do something that `mock` does not?

**Comment by robertzk** [comment]
I've never been able to get with_mock to work correctly. :( If you can show
me how and it works consistently, I can deprecate this feature.

On Tue, Mar 31, 2015 at 2:52 PM, Peter Hurford <notifications@github.com>
wrote:

> I just came here wondering about this myself.
>
> I'd err on the side of testthat functionality over testthatsomemore
> functionality wherever possible. Does package_stub do something that mock
> does not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/testthatsomemore/issues/3#issuecomment-88226139>
> .
>



-- 
-Robert Krzyzanowski

**Comment by peterhurford** [comment]
It works just fine -- I can show you.

**Comment by peterhurford** [comment]
The answer is mostly yes, but `package_stub` can mock `base` functions better than `with_mock` can and it's easier to use in metaprogramming (since `with_mock` is NSE). So I think there's some value in keeping it around.

**Comment by peterhurford** [comment]
Close?
